all: 3a 3b 3c

3a: 3a.rkt ../maelstrom/*.rkt
	raco make 3a.rkt
	raco exe 3a.rkt

3b: 3b.rkt ../maelstrom/*.rkt
	raco make 3b.rkt
	raco exe 3b.rkt

3c: 3c.rkt ../maelstrom/*.rkt
	raco make 3c.rkt
	raco exe 3c.rkt
